### ISSUE TITLE
Not working with Sqlite?

### ISSUE THREAD

**Issue by stephancb** [plotly/plotly-database-connector#76]
On Fedora 24 I enter the path to an sqlite db file, press connect and get the error popup below. sqlite3 is of course installed on the system.

```
Uncaught Exception:
Error: Please install sqlite3 package manually
    at new ConnectionManager (/home/scb/code/plotly/Plotly Database Connector-linux-x64/resources/app/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:25:13)
    at new SqliteDialect (/home/scb/code/plotly/Plotly Database Connector-linux-x64/resources/app/node_modules/sequelize/lib/dialects/sqlite/index.js:12:28)
    at new Sequelize (/home/scb/code/plotly/Plotly Database Connector-linux-x64/resources/app/node_modules/sequelize/lib/sequelize.js:233:18)
    at e.value (/home/scb/code/plotly/Plotly Database Connector-linux-x64/resources/app/backend/webpack:/backend/sequelizeManager.js:101:27)
    at e.value (/home/scb/code/plotly/Plotly Database Connector-linux-x64/resources/app/backend/webpack:/backend/sequelizeManager.js:128:18)
    at u (/home/scb/code/plotly/Plotly Database Connector-linux-x64/resources/app/backend/webpack:/backend/messageHandler.js:276:21)
    at EventEmitter.<anonymous> (/home/scb/code/plotly/Plotly Database Connector-linux-x64/resources/app/backend/webpack:/backend/messageHandler.js:114:3)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/home/scb/code/plotly/Plotly Database Connector-linux-x64/resources/electron.asar/browser/api/web-contents.js:209:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

**Comment by alexandresobolevski** [comment]
Hey, currently there is an issue for Sqlite for windows and linux OS' that is induced during the packaging of the app step. We are tracking it in #40.
